### ISSUE TITLE
FatalThrowableError in AbstractAdapter.php line 69

### ISSUE THREAD

**Issue by abada** [hassankhan/instagram-sdk#39] opened 2016-05-14 07:14 UTC
I am trying to make subscription request

```
      $call_back=MY_ROUTE;
      $par=['aspect'=>'media','callback_url'=>$call_back,'object'=>'user'];
      $response = $this->instagram_client->request('POST', 'subscriptions',$par);
      return $response->get();
```

After that this error shown

```
FatalThrowableError in AbstractAdapter.php line 69:
Fatal error: Class '\Larabros\Elogram\Exceptions\OAuthClientException' not found
```

**Comment by hassankhan** [comment] 2016-05-14 14:11
Subscriptions are not currently supported, dupe of #27, closing

**Closed as completed by hassankhan** 2016-05-14 14:11 UTC
